### ISSUE TITLE
Should `bids` namespace be defined in the BIDS-Prov context?

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#114]
Given that we can use BIDS URIs in a BIDS-Prov document (e.g. `bids::sub-01/fmap/sub-01_dir-AP_epi.nii.gz`), should the `bids` namespace be decalared in the BIDS-Prov context?

If yes, what URL should the BIDS namespace be mapped to?

@satra: do you have any insight on this? Thanks!

**Comment by satra** [comment]
i think it should be treated as a uri scheme automatically in jsonld. the bids uri needs a resolver service. so in this case `bids` is more like `http`, a protocol, than a uri.
