### ISSUE TITLE
Rewriting history of this repo

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#131]
Hi everyone!

Juste a quick note that @bclenet is currently looking into rewriting the history of this repo in order to remove the png files that make the repo >1GB. 

ping @satra

**Comment by cmaumet** [comment]
Thanks for the quick reply! Yes preserving the full history contributors commits etc. except the png.

**Comment by bclenet** [comment]
This was done using [BFG repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) and the following procedure :

```bash
# Clone the repo, using mirror option
git clone --mirror git@github.com:bids-standard/BEP028_BIDSprov.git

# Run BFG to clean history
java -jar bfg-1.14.0.jar --delete-files *.png BEP028_BIDSprov.git/
# alternatively, if you want to remove the .png images in the current revision (HEAD)
java -jar bfg-1.14.0.jar --no-blob-protection --delete-files *.png BEP028_BIDSprov.git/

# Physically delete the references BFG removed from the hisotry
cd BEP028_BIDSprov.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive

# Push the changes
git push
```

**Comment by bclenet** [comment]
@cmaumet the command lines were indeed applied to the current repo.

**Comment by cmaumet** [comment]
Fantastic thank you @bclenet!
