### ISSUE TITLE
_prov.jsonld at different levels

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#145]
## Update proposal for BIDS Prov (BEP028)
Proposal by @yarikoptic 
* 
* if not specific to any particular file, could in effect get `_prov` suffix, thus mimicing dataset level `prov.jsonld`. so there could be
>         * `prov.jsonld`
>         * `sub-1/sub-1_prov.jsonld` -- wide subject relevant provenance
>         * `sub-1/ses-2/sub-1_ses-2_prov.jsonld` -- specific for the session
>         * `sub-1/ses-2/func/sub-1_ses-2_prov.jsonld` -- for all the functionals
>         * `sub-1/ses-2/func/sub-1_ses-2_task-rest_bold.jsonld` -- specific to those `sub-1/ses-2/func/sub-1_ses-2_task-rest_bold.*`
>           This way tools would have flexibility to express themselves at the level they are operating at (file level, or group of files etc).

**Comment by yarikoptic** [comment]
I think it is mostly the 
- #144

**Comment by cmaumet** [comment]
Great! Then let's discuss at #144
