### ISSUE TITLE
fsl_default example [1 day]

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#17]
Similarly to what was done for spm_default in https://github.com/Inria-Visages/BIDS-prov/projects/3 but for [fsl_default](https://github.com/incf-nidash/nidmresults-examples/tree/master/fsl_default).

Deliverables : drawing of the pipeline in the current repository + JSON-LD example in the current repository + add any update to be considered for the spec in the list created in https://github.com/Inria-Visages/BIDS-prov/issues/10.

**Comment by remiadon** [comment]
Found this tutorial that I find interesting
https://web.stanford.edu/group/vista/cgi-bin/wiki/index.php/Segementation-FSL-Pipeline

@cmaumet agreed ?

**Comment by cmaumet** [comment]
Dioscussed with @remiadon on April 14. To get familiar with FSL, you can go throught the tutorials at: https://fsl.fmrib.ox.ac.uk/fslcourse/, in particular "3. FMRI Preprocessing and Model-Based Analysis" i) et ii)

**Comment by cmaumet** [comment]
Discussed with @remiadon on August 6. For Remi:
 - [ ] subdivide "stats" into "film_gls" and "smoothest".
 - [ ] Make a list of things that prevent us from going to the log to the JSON-LD representation automatically
