### ISSUE TITLE
rewrite README and repo transfer to BIDS-spec 

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#21]
rewrite taking https://github.com/bids-standard/bep001 as example

- [x] Ecrire le README à la racine pour permettre des contributions (via issues) -  https://github.com/Inria-Visages/BIDS-prov [  0.5j  ]
- [x] Relecture Camille et iteration/modif [  0.25j   ]
- [x] Faire une demande de transfer vers BIDS-standard -  https://github.com/BIDS-standard/BEP028  [ Camille  ]

**Comment by remiadon** [comment]
@cmaumet I just updated the readme

Main differences with the bep001 version
* No *inding information and getting in touch* section for the moment, we don't have any mailist list, nor montly mettings
* an additional "BIDS-prov in the NIDM project" sub-section, to be removed if this is your will. I thought this gives more context

**Comment by cmaumet** [comment]
@remiadon - Thanks! About "Finding info and getting in touch" -- could we use at least for now the NIDM group as entry point --> https://github.com/incf-nidash/nidm-specs/#nidm-weekly-calls

**Comment by remiadon** [comment]
Of course

I forgot to mention something important
We have no **Proposed changes to specification** (along with a dedicated *.md* file), see [here](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md)

**Comment by cmaumet** [comment]
@remiadon Thanks for this update. I only have a few suggestions:
 - "Who is building BEP028" can you add all the contributors we had listed in https://github.com/bids-standard/bids-specification/pull/439 (all of these people contributed to the first draft)
 - I'd remove "Avoiding great big pull requests" for now -- not sure this is quite the way we will work. Maybe replace by "How to ask a question / propose a change in BIDS PROV" and mention that people can submit issues to start the discussion and then join the calls.
 - I'd add a link to where the spec can be viewed (currently the google doc)
 - Add credit at the bottom of the README saying that it was inspired by the BEP001 readme.

**Comment by cmaumet** [comment]
>>  We have no Proposed changes to specification (along with a dedicated .md file), see here

Isn't this the role of your https://github.com/Inria-Visages/BIDS-prov/blob/master/new_features.md file? If so, how about linking to this from the "How to ask a question / propose a change in BIDS PROV" section?

**Comment by remiadon** [comment]
@cmaumet yes exactly, just was wondering if this is the right name

**Comment by cmaumet** [comment]
I see! Yes, using the same name would make sense, although in our case those are more points that will have to be discussed (as opposed to features we agreed to submit to the main spec).

**Comment by cmaumet** [comment]
Hey @remiadon, welcome back! If you can look into https://github.com/Inria-Visages/BIDS-prov/issues/21, then I'll ask for the repo to be moved under the BIDS organization.

**Comment by remiadon** [comment]
@cmaumet see 545abf3c5268d7d53fb791e240cd4a23434877bd :)

**Comment by remiadon** [comment]
@cmaumet everything seems OK on my side

**Comment by cmaumet** [comment]
Thanks @remiadon! Could you add JB Poline as well? (He is listed in the top comment here as he contributed to the google doc - https://github.com/bids-standard/bids-specification/pull/439#issue-393495658)

**Comment by remiadon** [comment]
@cmaumet  DONE

**Comment by cmaumet** [comment]
Done: https://github.com/bids-standard/BEP028_BIDSprov
