### ISSUE TITLE
Start "utils" library (include viz from JSON-LD 1.1) [1 day]

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#28]

**Comment by remiadon** [comment]
@cmaumet still struggling to run your code from https://github.com/Inria-Visages/BIDS-prov/pull/25

Are you sure there is no diff in the `context.json` file ? I don't see any in the pull request, but perhaps you had it modified locally

**Comment by cmaumet** [comment]
Arrg... I'm so sorry I think I forgot to push some changes... Looking into it now!

**Comment by remiadon** [comment]
@cmaumet can you provide the versions your are using for the following packages
* graphviz
* prov
* rdflib-jsonld
* pyld
* pydot

As well as a copy of your default.json file
