### ISSUE TITLE
Spec update issue template not displayed

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#29]
Hi @remiadon! I've merged your pull request creating the issue template for spec update proposals (https://github.com/bids-standard/BEP028_BIDSprov/pull/19) but for some reason it is not displayed at: https://github.com/bids-standard/BEP028_BIDSprov/issues/new/choose

Can you look into this? 

<img width="1353" alt="Screen Shot 2020-09-15 at 09 34 07" src="https://user-images.githubusercontent.com/5374264/93179928-a793d700-f736-11ea-8ae0-a10456bb3f88.png">

**Comment by remiadon** [comment]
DONE
