### ISSUE TITLE
OHBM abstract

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#33]
- [x] get ressources / examples from @cmaumet 
- [x] write v1
- [x] feedback on v1 (meeting) with @cmaumet 
- [x] write v2 and iterate over
- [x] share with BIDSProv comittee

**Comment by cmaumet** [comment]
why useless? - I liked it :D

**Comment by remiadon** [comment]
@cmaumet have you got resources to share ? I could start from this point and get a v1 by soon

**Comment by cmaumet** [comment]
Yes! Thanks for the ping. See here:
 - https://www.hal.inserm.fr/inserm-01972649/document
 - https://www.hal.inserm.fr/inserm-01570626/file/OHBM2016_Maumet.pdf
 - https://www.hal.inserm.fr/inserm-01933019/file/Bowring_OHBM2018.pdf

**Comment by remiadon** [comment]
@cmaumet v0 available here https://docs.google.com/document/d/1uygF-FZFpr0BbX6gcL4SKjyZQck9YXmpxoNIdQGyoJE/edit?usp=sharing
