### ISSUE TITLE
add clear explanations for spect update [5D]

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#35]
- [x] update new_features.md
- [x] create issue for type indexing
- [x] create issue for "Activity definitions"
- [x] create issue for "Activities attributes"
- [x] create issue for Multiple entities as input
- [x] validate

**Comment by remiadon** [comment]
update new_features.md in 76bd4694b70bec7308bd84104552801e7094e65d

**Comment by remiadon** [comment]
Here are the related issues
- https://github.com/bids-standard/BEP028_BIDSprov/issues/43
- https://github.com/bids-standard/BEP028_BIDSprov/issues/44
- https://github.com/bids-standard/BEP028_BIDSprov/issues/45
- https://github.com/bids-standard/BEP028_BIDSprov/issues/46

**Comment by remiadon** [comment]
@cmaumet waiting for you to validate

#44 and #45 are left as ongoing, as they were re-discussed yesterday

#43 and #46 seem OK to me

**Comment by cmaumet** [comment]
This is excellent! Thanks @remiadon. Let's close this issue and continue the discussions in the relevant issues.
