### ISSUE TITLE
Meeting with committee [3D]

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#36]

**Comment by cmaumet** [comment]
At the next NIDASH call (October 12), with @remiadon we would like to discuss the BIDS-Prov examples Remi has been working on. 

@satra: do you think that you will be able to make that call? Thanks!

**Comment by satra** [comment]
could we have a quick chat sometime before to look at reproschema-py and how you can use it to evaluate context encoding?

**Comment by cmaumet** [comment]
Yes! How is Tuesday (Oct 6) or Friday (Oct 9) next week?

**Comment by satra** [comment]
tue oct 6 works (i can do 8.30am ET, 10.15am ET or Noon ET).

**Comment by cmaumet** [comment]
I can do 10.15am ET, I've sent a calendar invite.

**Comment by remiadon** [comment]
I just checked out the reproschema doc

To me we can use it to evaluate graphs are consistent with a standard definition (SHACL), but I am not sure about using `protocol`, `actitity` and `item`. Should we use those concepts ?

Rémi

**Comment by cmaumet** [comment]
Hi @remiadon! The idea is to use the same methods as reproschema to build our context files (as they used a few "tricks" that make the final documents very human-readable) but not the concepts themselves. Does that make more sense?

**Comment by remiadon** [comment]
OK so this is only about the context. Just got confused
So we would have to use "reproschema:" prefix in our context definition from what I understand, just like in `"@type": "reproschema:Activity"` from [the reproschema examples](https://github.com/ReproNim/reproschema/blob/master/examples/activities/activity1.jsonld)

**Comment by remiadon** [comment]
as discussed on November 2nd, I'll open 2 dedicated issues for
1) replacing Activity:"attributes" field by nidm:DataElements
2) usage prov:wasInfluencedBy to model inplace edition of an Entity

closing this
