### ISSUE TITLE
First blog article

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#41]
@cmaumet we should also think about a first article to be posted by the end of this month, as discussed in meeting.

It can be very simple (eg. just showcasing what's been done), but we should seek a formal definition of what's inside

Cheers,
Rémi

**Comment by cmaumet** [comment]
Yes, sounds like a plan! What do you need to get started with a first draft?

**Comment by remiadon** [comment]
@cmaumet I think I can showcase the following workflow :
- outputting bids_prov graphs in .json files (just like SPM would do, but'll create them)
- querying this schema with sparcl

What do you think ?

**Comment by cmaumet** [comment]
Yes, that sounds very nice!

**Comment by cmaumet** [comment]
(And in the discussion we can make it clear that this will not be limited to SPM)
