### ISSUE TITLE
clear explanation of an Activity

### ISSUE THREAD

**Issue by remiadon** [bids-standard/BEP028_BIDSprov#44]
as discussed with @cmaumet , @dbkeator and @satra on November 2nd

What do we mean by Activity ?
Currently the examples encapsulate everything related to the run : an activity is the call of an Agent on a specific set of entities, and includes parameters (as defined in a batch.m for example)

Perhaps we should rather separate user-oriented graph definition from a more complete description, which would contain Activities, and the full set of parameters

**Comment by remiadon** [comment]
Don't know it that helps but there is an analogy with docker images VS containers
Containers are running instances of docker images

This binding is very simplistic yet  is emphasizes that activities can be containerized

**Comment by remiadon** [comment]
@cmaumet does that comparison make sense ? If yes, should we write something about it ?
If not, do we still need to clarify what an activity is ? where ?

**Comment by cmaumet** [comment]
@remiadon - thanks for following up on this thread. I think the question about activity is also about the level of granularity at which we represent the pipeline. We touched on that in our submitted abstract but I think the usecases should also help build some clarity. I think we can close this issue.
