### ISSUE TITLE
Storing RRID's

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/BEP028_BIDSprov#68]
This is an update proposal for BIDS Prov (BEP028).

### Problem Statement
As discussed on the [BIDS-Prov meeting (November 8, 2021)](https://docs.google.com/document/d/1Z2CCum9vqxRenTElhgv1l1H9gt1BGwkvT8mGWKtX4Rk/edit), in BIDS-Prov we need a way to store the RRID of a software agent.

Note: RRIDs are unique identifiers for software agent, as defined on the scicrunch.org website. More info at: [scicrunch.org Getting Started](https://scicrunch.org/resources/about/Getting%20Started) and in [this paper (10.1016/j.neuron.2016.04.030)](https://dx.doi.org/10.1016%2Fj.neuron.2016.04.030). Importantly RRIDs are not version-specific, e.g. SPM5 and SPM12 have the same [RRID:SCR_007037](https://scicrunch.org/resources/Tools/record/nlx_144509-1/SCR_007037/resolver?q=spm&l=spm)).

## Currently in the draft BIDS-Prov
Currently in [the BIDS-Prov specification](https://docs.google.com/document/d/1vw3VNDof5cecv2PkFp7Lw_pNUTUo8-m8V4SIdtGJVKs/edit#), RRIDs are stored with a specific attribute `rrid`:

----
2.3 Agent (Optional)

Including an Agent record is OPTIONAL. If included, each Agent record has the following fields:

Key name | Description
-- | --
@id | REQUIRED. UUID. An (randomly-assigned) identifier for the software (this identifier will be used to associated activities with this software).
rrid | OPTIONAL. URI. URI of the RRID for this software package (cf. scicrunch).
...

----

Pros: 
 - A specific tag for rrids will make it very easy to query and retrieve this information
 - A specific tag for rrids prevents using other types of identifiers 

Cons:
 - A specific RRID tag means that we will have to create a term (or reuse an existing one if already available)

### Dandi
... uses an "identifier" term, which is separate from the "@id"

<img width="498" alt="Screen Shot 2021-11-23 at 14 36 03" src="https://user-images.githubusercontent.com/5374264/143033881-bb789d15-8a96-4bd9-bfcb-b5c567672453.png">

Pros: 
 - A specific tag for identifiers will make it very easy to query and retrieve this information
 - A generic "identifier" tag allows for using other types of identifiers 

Cons:
 - When querying for the identifier, it might not be clear which type of identifier is retreived (RRID or something else?) -- although this might not be entirely true if an URI is used as a value in which case the base url can be an indication of the type of identifier.
 - id and identifier are very close words and might be confused

Question: has the dandi model been released? Can we directly reuse the terms?

**Comment by cmaumet** [comment]
Michael: do you have a way to store RRIDs with your model (`concise`)?

**Comment by bclenet** [comment]
Just a quick note about an issue I noticed about RRIDs.

For now, all parsers use the `bids_prov.utils.get_default_graph` function to generate a default graph as starting point.
This function always sets :
```
"RRID": "RRID:SCR_007037",
```
which is the RRID for SPM.

**Comment by cmaumet** [comment]
Discussed with @bclenet today. This is now implemented with `AltIdentifier` in the spec: https://docs.google.com/document/d/1vw3VNDof5cecv2PkFp7Lw_pNUTUo8-m8V4SIdtGJVKs/edit#heading=h.w2m5fn6qsdya
